ruby:
  - "Marshal"
  - "render params"
  - "%x\\/"
  - "IO\\.popen"
  - "eval"
  - "instance_eval"
  - "class_eval"
  - "send"
  - "__send__"
  - "public_send"
  - "try"
  - "\\^"
  - "\\$"
  - "Kernel\\.exec"
  - "Kernel\\.system"
  - "Kernel\\.open"
  - "File\\.read"
  - "html_safe"
  - "\\.calculate"
  - "\\.delete_all"
  - "\\.destroy_all"
  - "\\.exists\\?"
  - "\\.find_by"
  - "\\.from"
  - "\\.group"
  - "\\.having"
  - "\\.joins"
  - "\\.lock"
  - "\\.order"
  - "\\.pluck"
  - "\\.reorder"
  - "\\.select"
  - "\\.where"
  - "\\.update_all"
  - "`"
c:
  - "argv\\[[0-9+]\\]"
cpp:
  - "argv\\[[0-9+]\\]"
